### ISSUE TITLE
ack functionality from within the open violations tab

### ISSUE THREAD

**Issue by sdeedee** [newrelic-experimental/nr1-command-center#7]
## Summary

It would be nice to have ack functionality in the open violations tab. 

## Desired Behaviour

Adding an ack button (linked to NR acknoweldge link) so people can work on this overview dashboard and can ack within this dashboard without the need to login on that particular (sub)account to do so.

**Comment by khpeet** [comment]
What is the proposed design here? Another column with a button to acknowledge a given incident?

**Comment by khpeet** [comment]
@sdeedee ^^

**Comment by khpeet** [comment]
@sdeedee - I played around with this and it looks like ack functionality is possible, but the API call requires a user's **admin API key** - therefore, the proposed design would be an "Ack" column with a button that would open a popup for a user to input their admin key, make the API call, and then update each violation row that has the same incident ID with the user's initials (and full name onHover), that acknowledged that incident. Let me know if that suffices-otherwise you can just click the incident link and acknowledge that incident in the New Relic Alerts UI.

**Comment by sdeedee** [comment]
Thanks for investigation. In my particular use case, users don't have their own admin api key. Acking an incident through incident link will redirect to the (sub)account alerting page or not? If not, this would we workable. 
Another idea is working with a api_user admin api key that's calling the ack api, but then we probably would see always the api_user admin that acked a problem and not individual users.

**Comment by khpeet** [comment]
@sdeedee - Correct, you would be redirected to that specific incident's page. Actually the user that is **currently viewing** this nerdpack would be the user that shows as the one who acknowledged the alert (not the user who owns the admin api key).

**Comment by khpeet** [comment]
so the tradeoff is the ack functionality will require admin key input each time someone wants to ack (so you need the admin key from that account where the incident resides)  OR without ack, you have to login to the account (via clicking the incident link column) and acknowledge there. Let me know which you prefer!

**Comment by sdeedee** [comment]
In my use case ack via clicking the incident link column would be the better solution
